### ISSUE TITLE
Cleanup unused packages

### ISSUE THREAD

**Issue by pi0neerpat** [UseKeyp/usekeyp-js-sdk#10]
- [ ] Remove the old packages which will not be released `components-soft-ui` and `tailwind-presets`
- [ ] Destroy all git history, and make a new initial commit. This is to protect copyrighted code from a 3rd-party vendor being exposed. You'll need to use force-push for this. I have removed branch protection rules
- [ ] After complete, ask Patrick to re-enable branch protection rules, and to change the repo visibility to public

**Comment by alekseevaiana** [comment]
## Steps
### Remove
- Remove the old packages which will not be released `components-soft-ui` and `tailwind-presets`
- Check if everything is working fine
### Destroy git history
I am a little bit worried about deleting branches, so hope this plan is right.
- create backup to my computer (`git clone [ui-library]`)
From dev branch
- `git checkout --orphan new_initial_commit`
- `git add -A`
- `git commit -m "New initial commit"`
- `git branch -D dev`
- `git branch -m dev`
- `git push -f ui dev`
Delete main branch too?
- `git branch -D main`
- `git checkout -b main`
- `git push -f ui main`

**Comment by pi0neerpat** [comment]
Your fears are valid, and your plan to copy everything is good to mitigate risk. I've pulled locally on my machine as an extra backup. I recommend just running `rm -rf .git` and then `git init` followed by a force push, and deleting old branches on github.
:+1:

**Comment by alekseevaiana** [comment]
@pi0neerpat I cleaned up everything, so you can re-enable branch protection rules

**Comment by pi0neerpat** [comment]
Awesome thanks! Nice work. Closing this issue
