### ISSUE TITLE
Precompile jsx files to improve DX

### ISSUE THREAD

**Issue by alekseevaiana** [UseKeyp/usekeyp-js-sdk#19]
Find the best way to precompile components from jsx to simple js
- found an article on how to do it without changing webpack, will try: https://medium.com/casavo/you-dont-need-webpack-for-your-react-components-library-96b97d7d25ae
## Plan:
- `yarn add --dev @babel/core @babel/cli`
- `yarn add --dev @babel/preset-env @babel/preset-react`
- `yarn babel src -d lib`

**Comment by pi0neerpat** [comment]
Looks good!
