### ISSUE TITLE
Initial setup

### ISSUE THREAD

**Issue by pi0neerpat** [UseKeyp/usekeyp-js-sdk#2]
- [ ] Clone the frontend-components repo to here
- [ ] Ensure styleguidist is running properly
- [ ] Create a new package called `ui-library` within the repo /packages

**Comment by alekseevaiana** [comment]
Hey, @pi0neerpat, I need some help clarifying instructions. 
> Clone the frontend-components repo to here

What do mean "clone repo to here"? What would be end result?
Should "ui-library" repo be clone of "keyp-frontend-components" repo to do work in "ui-library" repo?
Or should "keyp-frontend-components" repo be added as a subdirectory in "ui-library" repo?


Or do you mean "ui-library" should be a subdirectory in "keyp-frontend-components/packages"?

**Comment by alekseevaiana** [comment]
Plan:
1. `git clone git@github.com:UseKeyp/keyp-frontend-components.git` (to get initial repo)
2. `git checkout dev`
3. inside cloned repo `git remote add ui git@github.com:UseKeyp/ui-library.git` (to add new repo as another remote)
4. Push dev to ui-library repo: `git push -u ui dev`
5. Create new branch for work `git checkout -b iana/initial-setup`
6. install dependencies `yarn`
7. create new package in `./packages` folder: `lerna create ui-library`
8. go into `./packages/ui-library` and install styleguidist `yarn add react-styleguidist` (and other required packages)
9. copy `./packages/components-soft-ui/styleguide.config.cjs` to `./packages/ui-library/styleguide.config.cjs`
10. run `styleguidist build --config styleguide.config.cjs` inside `packages/ui-library` to run styleguidist

**Comment by pi0neerpat** [comment]
Looks great! Let's go for it!
