### ISSUE TITLE
[ui] UserAccount component

### ISSUE THREAD

**Issue by pi0neerpat** [UseKeyp/usekeyp-js-sdk#20]
Add components:
- UserAccount. From keyp-app, wait until #246 is merged

**Comment by alekseevaiana** [comment]
## Plan
- create component
- create a ToolTip
- add more icons
- make a function to pick colors for the username text (think that I can reuse what I used in choosing a background for login buttons)
- test that everything works

**Comment by pi0neerpat** [comment]
> make a function to pick colors for the username text (think that I can reuse what I used in choosing a background for login buttons)

This already exists in keyp-app or frontend-components somewhere

Sounds good!
