### ISSUE TITLE
CRA example updates

### ISSUE THREAD

**Issue by pi0neerpat** [UseKeyp/usekeyp-js-sdk#22]
- Update the Readme to include that the only changes after setting up the create-react-app were to add the ui-library
- Update the scripts in package.json according to the recommendations made by the ui-library 
- Change the installed package version to the latest stable published package (eg. after you merge the new changes and we publish a final public version). Depends on #12 
- Fix the component width to match designs (either in the parent app, or in the component itself.
- Update the components to ensure that background colors are the normal ones we expect, not the ones from the app

![image](https://user-images.githubusercontent.com/35622595/233222935-c3667e52-2ba0-4f5e-8c20-ce4a3e209963.png)

**Comment by alekseevaiana** [comment]
## Plan
- do it after #10 and #12 
- update Readme in the example project describing steps on how we set up everything
- update package.json in the example project to include commands to run it (build, tailwindss)
- fix width and bg-color in LoginPortal component

**Comment by pi0neerpat** [comment]
Sounds good!
