### ISSUE TITLE
Custom domain hosting

### ISSUE THREAD

**Issue by pi0neerpat** [UseKeyp/usekeyp-js-sdk#23]
dev branch should be hosted at `ui.staging-env.usekeyp.com`
main branch should be hosted at `ui.usekeyp.com`

Let me know the DNS settings I need to enter

**Comment by alekseevaiana** [comment]
This is the documentation on how to set up a custom domain: https://surge.sh/help/adding-a-custom-domain
1. Add a new CNAME record to your domain.
2. Set the hostnames @ and www to: na-west1.surge.sh
3. If your DNS provider doesn’t support CNAME records for apex domains, you can set an A record to the following IP address instead: 45.55.110.124
4. Additionally, setting the hostname * to na-west1.surge.sh will allow you to deploy to custom subdomains on your domain as well.
Once you set up CNAMEs, let me know, I should be able to host our ui-lib with surge to the custom domains.

**Comment by alekseevaiana** [comment]
## Clarification on Surge Account Limitations and Custom Domain Usage
### Review
On the free Surge account, we are limited to using only HTTP with custom domains. To enable HTTPS, an upgrade to Surge Plus is required.
The relevant documentation on the supported features can be found here: https://surge.sh/help/upgrading-to-surge-plus
To upgrade: https://surge.sh/pricing

@pi0neerpat could you tell what did we decide here? I see that redirecting from custom domains works for now.

**Comment by pi0neerpat** [comment]
I made the https links just redirect to the existing surge deployment urls. So we can close this now. Thanks!
