### ISSUE TITLE
QA updates

### ISSUE THREAD

**Issue by pi0neerpat** [UseKeyp/usekeyp-js-sdk#25]
- remove Button example 
- Icon example should use Discord
- LoginButton should have icon and correct hover state
- MoreAccordion buttons should have icons
- code example should always be expanded 
- favicon for page
- header bar and title

**Comment by alekseevaiana** [comment]
## Plan
Everything seems clear. To customize a theme, I am reading styleguidist documentation. I think there is a way to do it in styleguidist.config file.

## Sources
Figma
https://www.figma.com/file/iEcXQe5U4Isjk0Yj2Btgis/Design-Library?node-id=898-1166&t=JIVrUW0fsiQYsHog-0
