### ISSUE TITLE
[ui] Remove redwood dependency

### ISSUE THREAD

**Issue by pi0neerpat** [UseKeyp/usekeyp-js-sdk#29]
Since this is now a monorepo, the [ui] means its for the "ui-kit" package. I will try to specify each time which package is involved.

**Comment by alekseevaiana** [comment]
## Plan
- redwood is used in the `Button` component for `Link`, so change the component to use `<a>` tag instead of `Link`. 
- remove redwood dependency from package.json (`"@redwoodjs/router": "^3.3.0"`)
- update yarn install
- run the project and make sure that nothing is broken

**Comment by pi0neerpat** [comment]
looks good!
