### ISSUE TITLE
Add components

### ISSUE THREAD

**Issue by pi0neerpat** [UseKeyp/usekeyp-js-sdk#3]
- [ ]  Add all the components needed to create the login portal: eg. Button, Icon,
- [ ] Create a new component <LoginPortal/> which combines these components together into a single component.
- [ ] The Buttons should accept the function needed to trigger a login. This is different depending on the implementation, so it must be general-purpose. Here's a few examples:
   - Next app https://github.com/raid-guild/blood-of-moloch/pull/43/files
   - Redwood app https://github.com/UseKeyp/usekeyp-example-app-redwood/blob/dev/web/src/pages/LoginPage/LoginPage.js
   - Express app https://github.com/UseKeyp/usekeyp-example-app-express/blob/main/views/login.ejs

**Comment by alekseevaiana** [comment]
Few questions I have:
- can I reuse components from `soft-ui` package?
- how will LoginPortal component code look like? Does it accept a list of providers names or will it contain children with various buttons?
Example: 
```
<LoginPortal providers={['discord', 'google', 'twitter']}/>
```
or
```
<LoginPortal>
     <LoginButton provider="discord" size="full"></LoginButton>
     <LoginButton provider="discord" size="small"></LoginButton>
     <LoginSelector/> // form component with more buttons
</LoginPortal>
```

Overall plan:
- find a way how to reuse components from different packages (done)
- set up tailwindcss properly to show styles (done)
- how to run multiple packages (use yarn link if I understand correctly)
- create LoginFrame component (frame with border, title, and bottom text ("powered by keyp")
- create LoginPortal after clarifying details (above)

**Comment by pi0neerpat** [comment]
- Can I reuse components from soft-ui package? Yes, the code can be copy/pasted over into this package. The `soft-ui` package will be deleted from this repo before we publish. Please limit the copied code to only the minimum required to produce the desired results.  
- I like the first option. Maybe we give people the chance to decide which options they want for each location. Not sure if I like `moreProviders` as the name for this prop, but its a good start.

```js 
<LoginPortal providers={['discord', 'google', 'twitter']} moreProviders={['twitch']}/>
```

The rest looks good!

**Comment by alekseevaiana** [comment]
Hello, 
- issues have been resolved
- added svg loading animation to the button (as a prop)
