### ISSUE TITLE
Design Quality Assurance

### ISSUE THREAD

**Issue by pi0neerpat** [UseKeyp/usekeyp-js-sdk#4]
- [ ] Ensure the final results match designs. Work together with Sascha on this

Since there may not be a hosted version of react-styleguidist you can send, you could send screenshots, or share your screen on a call.

**Comment by alekseevaiana** [comment]
Hello, 
- Providing screenshots before Sasha gives his feedback.
- If some changes are required, will change and provide the final results as well
<img width="376" alt="Screenshot 2023-03-30 at 10 42 58 AM" src="https://user-images.githubusercontent.com/36742189/229198998-12404692-a20a-4291-8ca3-e74baa916d86.png">

<img width="383" alt="Screenshot 2023-03-30 at 10 43 24 AM" src="https://user-images.githubusercontent.com/36742189/229199049-d6fd2642-4ab3-448a-a07d-4a82b058c620.png">

<img width="413" alt="Screenshot 2023-03-30 at 8 42 17 PM" src="https://user-images.githubusercontent.com/36742189/229199142-26aceff1-55e8-4a4c-8fca-5ffb568c1b8c.png">
