### ISSUE TITLE
Publish PR Packages

### ISSUE THREAD

**Issue by pi0neerpat** [UseKeyp/usekeyp-js-sdk#5]
- [ ] Add the tool to the repo using github actions https://github.com/UseKeyp/publish-pr-packages
- [ ] Test the pr package created by this tool: Get it working in the Kaching app, or another example app. Share screenshots. If not using kaching, use any React app framework of your choice, excluding redwood. Ask Patrick to create a new private repo in our organization for pushing this.

### Resources 

- See example implementation https://github.com/UseKeyp/keyp-frontend-components/blob/dev/.github/workflows/ci-pr.yml
- I've already added the necessary secret as `PAT`

**Comment by alekseevaiana** [comment]
Plan and questions:

- Install lerna in the root of your repo with the following command:

`yarn add --dev lerna`
`lerna init`

- Ensure `package.json` includes the packages you want to publish in the workspaces:

```bash
{
  "workspaces": [
    "packages/ui-library"
  ]
}
```

- Copy the `/tasks` directory to the root of the repo, then `chmod +x [filename]` each of them to allow for execution

Questions:
- How to test?
- How can I find the necessary secret as `PAT` or is it already in "Puplish PR package"?
- What is Kaching app (couldn't find anything)?
- `Ask Patrick to create a new private repo in our organization for pushing this`. So I don’t commit and push it into this repo?

**Comment by pi0neerpat** [comment]
I believe these were all answered this morning. You're good to proceed on this

**Comment by pi0neerpat** [comment]
closed in #13
