### ISSUE TITLE
Host the styleguidist

### ISSUE THREAD

**Issue by pi0neerpat** [UseKeyp/usekeyp-js-sdk#6]
- [ ] Pick a hosting provider to auto-deploy react-styleguidist for both dev and main branches. Add the deployment URLs to the readme. dev should be the default Github branch. main should be the production-ready branch.

### Resources

- The frontend-components library is already hosted using surge. Ask Jacob if you'd like to use the same method.

**Comment by alekseevaiana** [comment]
Plan
 - CD into the ui-library folder
 - Run styleguidist build (yarn build) to generate the styleguide directory with the bundled assets for deploy
 - Install surge `npm install --global surge`
 - Run surge and point to the styleguide folder
 - Chose `keyp-ui-library.surge.sh` as a domain (or another if it doesn't work)

**Comment by pi0neerpat** [comment]
Looks good! Contact Jacob about if we have a team account for surge
