### ISSUE TITLE
Dependabot updates

### ISSUE THREAD

**Issue by pi0neerpat** [UseKeyp/usekeyp-js-sdk#63]
There are several dependabot security notifications, not urgent, which are related to our example apps- not our packages.

Let's get these cleaned up https://github.com/UseKeyp/usekeyp-js-sdk/security/dependabot

**Comment by alekseevaiana** [comment]
## Plan
1. Prototype Pollution in minimist
I can add to the main package.json and examples apps. But not sure that this is enough. After `yarn install` I can still see that some packages uses minimist versions lower than 1.2.6. 
```json
"resolutions": {
     "minimist": "^1.2.6"
 }
```
2. Inefficient Regular Expression Complexity in nth-check: updated with the same method as 1
3. Missing proper state, nonce and PKCE checks for OAuth authentication: was able to run in from interface and auto PR 77 was created
4, 5. Inefficient Regular Expression Complexity in nth-check: same as 2.  
6. Tough-cookie Prototype Pollution vulnerability: Was able to run in from interface and auto PR was created PR 77
7. Tough-cookie Prototype Pollution vulnerability: same as 6. I believe that it will be gone after PR 77 is merged
8, 9, 10. Word-wrap vulnerable to Regular Expression Denial of Service: moderate, and there are no version to fix it, so I think we doing nothing for now
11, 12, 13. Semver vulnerable to Regular Expression Denial of Service: 
14. Server-Side Request Forgery in Request: moderate, and there are no version to fix it, so I think we doing nothing for now

**Comment by pi0neerpat** [comment]
Looks good
